# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://rs-anderson.github.io/chuma/'
baseurl: 'https://rs-anderson.github.io/chuma/'
title: 'Chuma'
description: 'Financial Tools Chatbot for Informal Traders'
permalink: pretty
logo: "/assets/logos/chuma_logo.jpeg"

# Header nav
navigation_header:
- title: Home
  url: /
- title: Demo
  url: /demo/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"